### ISSUE TITLE
[BUG REPORT] For loop not accepting variables as starting or ending variable

### ISSUE THREAD

**Issue by lucasace** [cimplec/sim-c#133]
**Describe the bug**
While writing the for loop in simc, a variable name cannot be used as a starting value or a ending value, the simc compiler throws a error

**To Reproduce**
simc code:
```bash
MAIN
	var f=10
	var j =0 
	for i in j to f by +1{
		print(i)
	}
END_MAIN
```
produces a error saying **[Line 4] Error: Expected starting value**

**Expected behavior**
simc Code:
```bash
MAIN
	var f=10
	var j =0 
	for i in j to f by +1{
		print(i)
	}
END_MAIN
```

C code:
Not generated

Expected C code:
```bash
#include<stdio.h>
int main(){
	int f = 10;
	int j=0;
	for(int i =j;i<f;i++){
		printf("%d",i);
	}
return 0;
}
```

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by frankhart2018** [comment]
Thanks @lucasace for reporting the bug. Please also link this to #66 too.  You can comment on that something like:-

Bug reported - For loops not accepting variables as starting or ending varibale - #133.

**Comment by lucasace** [comment]
Okay sure!

**Comment by lucasace** [comment]
I would like to take a shot at this

**Comment by frankhart2018** [comment]
Sure @lucasace try this. Thanks.

**Comment by frankhart2018** [comment]
Merged, thanks for your contribution @lucasace.
