### ISSUE TITLE
[BUG REPORT] Compiler throws warnings when an input statement is used with no print statements

### ISSUE THREAD

**Issue by Martianmellow12** [cimplec/sim-c#137]
**Describe the bug**
If a program has an `input` statement, but no `print` statements, then the resulting C file is unable to compile without warnings in GCC due to `stdio.h` not being included.

**To Reproduce**
To reproduce the behavior, run the following code:
```
MAIN
	//print("This is a print statement!\n")
	var tmp = input("Enter something: ", "i")
	//print("You entered: ")
	//print(tmp)
	//print("\n")
END_MAIN
```
Attempting to compile the resulting C file produces implicit declaration warnings for `printf` and `scanf`

**Expected behavior**
The code should include `stdio.h` if an `input` statement is present. This way the C code produced by simc would compile with no warnings.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)

**Comment by Martianmellow12** [comment]
If you'd assign me, I'd like to take a shot at fixing this bug

**Comment by frankhart2018** [comment]
Thanks @lucasace for reporting the bug. Please also link this to #66 too. You can comment on that something like:-

Bug reported - Compiler throws warnings when an input statement is used with no print statements - #137.

**Comment by frankhart2018** [comment]
Sure assigning this to you @Martianmellow12. Thanks.

**Comment by frankhart2018** [comment]
Merged, thanks for your contribution @Martianmellow12.
