### ISSUE TITLE
[BUG REPORT] Using "s" to read in a string doesn't generate the proper C code

### ISSUE THREAD

**Issue by Martianmellow12** [cimplec/sim-c#183]
**Describe the bug**
When `input` is called with `"s"` as the input type, the generated C code doesn't work properly.

**To Reproduce**
Below is a simc program accompanied by the generated C program:

simc
```
MAIN
  var i = input("Enter a string: ", "s")
  print("You entered ")
  print(i)
  print("\n")
END_MAIN
```

Generated C
```
#include <stdio.h>

int main() {
	char* i;
	printf("Enter a string: ");
	scanf("%s", i);
	printf("You entered ");
	printf("%s", i);
	printf("\n");

	return 0;
}
```

**Expected behavior**
It's expected that whatever string was entered would be printed out, however all that's printed is `(null)`. Looking at the C code, it can be seen that the pointer we're trying to read a string into (`char* i`) is only able to hold a single character, which is likely causing the `null` issue. To properly read in a string, `char* i` should instead be something like `char i[256]`, or something similar (the exact size would depend on the size of the string being read in, so this implementation would require a limit on the maximum number of characters that can be read into the string).

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)

**Comment by frankhart2018** [comment]
@Martianmellow12 it seems that the issue only appears when compiled in linux, in macOS and Windows it works fine. Still it needs to be changed. But the issue with a constant length of 256 is - 

1) It cannot hold a string longer than 256 bytes.
2) If the string is small let's assume "abc" then also the string holding it will take up 256 bytes in memory. 

I believe there should be some other option. If you get one do send it in this thread, if any of us get it we will send it here.

**Comment by Chasmiccoder** [comment]
I think this is because the C compiled code is using the scanf( ) statement incorrectly. Instead of
scanf( "%s", &i);
we are getting:
scanf("%s", i );

![image](https://user-images.githubusercontent.com/62545147/101245644-3b70b000-3734-11eb-8586-bb67c84bb0b2.png)

**Comment by frankhart2018** [comment]
You can take up this issue @Chasmiccoder.

**Comment by Chasmiccoder** [comment]
Okay. I will try. @frankhart2018

**Comment by frankhart2018** [comment]
Assigning this to you @Chasmiccoder.

**Comment by frankhart2018** [comment]
Merged.
