### ISSUE TITLE
[BUG REPORT] Variable in print is formatted even without {}

### ISSUE THREAD

**Issue by nanoy42** [cimplec/sim-c#188]
**Describe the bug**
According to the documentation, https://gist.github.com/frankhart2018/56246355613061a3e1799621aed10f34#file-print-emb-var-simc, names of variables that are not in {} should not be formatted when translating to C. Here is an example from solving issue #161 

```
MAIN
    // Compute the area of a rhombus, given its bases
    // The bases are float inputs

    // Get the two bases
    var p = input("First basis : ", "f")
    var q = input("Second basis : ", "f")

    var area = p*q/2

    print("The area of the rhombus ({p}, {q}) is {area}") 
END_MAIN
```
and the c-code
```
#include <stdio.h>

int main() {
	//  Compute the area of a rhombus, given its bases 
	//  The bases are float inputs 
	//  Get the two bases 
	float p;
	printf("First basis : ");
	scanf("%f", &p);
	float q;
	printf("Second basis : ");
	scanf("%f", &q);
	float area = p * q / 2;
	printf("The %f of the rhombus (%f, %f) is %f", p, q, area);

	return 0;
}
```

**To Reproduce**
1. Install simc as stated in documentation  `pip install git+https://github.com/cimplec/sim-c`
2. Translate the code given above

**Expected behavior**
The following code should be generated 
```
#include <stdio.h>

int main() {
	//  Compute the area of a rhombus, given its bases 
	//  The bases are float inputs 
	//  Get the two bases 
	float p;
	printf("First basis : ");
	scanf("%f", &p);
	float q;
	printf("Second basis : ");
	scanf("%f", &q);
	float area = p * q / 2;
	printf("The area of the rhombus (%f, %f) is %f", p, q, area);

	return 0;
}
```

**Desktop (please complete the following information):**
 - OS: Arch, with Kernel 5.8.12, using python 3.8.5 and pip 20.1.1

I can try to investigate and fix the error.

**Comment by DevLokCodes** [comment]
noticed the same bug with my code
it is not able to detect the parenthesis properly 
The bug got fixed when i typed the string with difference in Upper class and lower class 

images with bugs
![image](https://user-images.githubusercontent.com/69622048/95016528-26629c80-0671-11eb-9575-837c4812e1f4.png)
![image](https://user-images.githubusercontent.com/69622048/95016523-1f3b8e80-0671-11eb-96db-6ae9696c355c.png)



images without bugs
![image](https://user-images.githubusercontent.com/69622048/95016546-409c7a80-0671-11eb-9be0-1d53d4e76e9b.png)
![image](https://user-images.githubusercontent.com/69622048/95016551-472af200-0671-11eb-94f8-c65f46245c8e.png)

**Comment by Aayush-99** [comment]
Thanks, for reporting this issue although it has already been reported by someone else and has been assigned to him. Please checkout #149
