### ISSUE TITLE
[BUG REPORT] OR (||) is not translated correctly

### ISSUE THREAD

**Issue by nanoy42** [cimplec/sim-c#189]
**Describe the bug**
Or symbol || was not translated. Here is an example from solving issue #161 

```
MAIN
    // Compute the area of a rhombus, given its bases
    // The bases are float inputs

    // Get the two bases
    var p = input("First basis : ", "f")
    var q = input("Second basis : ", "f")

    // Verify that the bases are positive
    if(p<0 || q<0) {
        print("Bases cannot be negative")
    } else {
        var area = p*q/2

        print("Area of the rhombus ({p}, {q}) is {area}")
    }
END_MAIN
```
and the c-code
```

#include <stdio.h>

int main() {
	//  Compute the area of a rhombus, given its bases 
	//  The bases are float inputs 
	//  Get the two bases 
	float p;
	printf("First basis : ");
	scanf("%f", &p);
	float q;
	printf("Second basis : ");
	scanf("%f", &q);
	//  Verify that the bases are positive 
	if(p < 0q < 0) {
	printf("Bases cannot be negative");
	}
	else {
	float area = p * q / 2;
	printf("Area of the rhombus (%f, %f) is %f", p, q, area);
	}

	return 0;
}
```

**To Reproduce**
1. Install simc as stated in documentation  `pip install git+https://github.com/cimplec/sim-c`
2. Translate the code given above

**Expected behavior**
The following code should be generated 
```

#include <stdio.h>

int main() {
	//  Compute the area of a rhombus, given its bases 
	//  The bases are float inputs 
	//  Get the two bases 
	float p;
	printf("First basis : ");
	scanf("%f", &p);
	float q;
	printf("Second basis : ");
	scanf("%f", &q);
	//  Verify that the bases are positive 
	if(p < 0 || q < 0) {
	printf("Bases cannot be negative");
	}
	else {
	float area = p * q / 2;
	printf("Area of the rhombus (%f, %f) is %f", p, q, area);
	}

	return 0;
}
```

**Desktop (please complete the following information):**
 - OS: Arch, with Kernel 5.8.12, using python 3.8.5 and pip 20.1.1

I can try to investigate and fix the error.

**Comment by Aayush-99** [comment]
Thanks @nanoy42 for reporting the bug. Please also link this to #66 too. You can comment on that something like:-

Bug reported - OR (||) is not translated correctly -  #189

**Comment by nanoy42** [comment]
Ok, so I investigated a little more and here is what I found.
The characters are not printed in the token list, when doing simc q54.simc token (as a comparison the && is recognized as two 'address_of' tokens).

After reviewing the code of `lexical_analyze', it seems that there is a missing edge case for the "|" symbol.

**Comment by frankhart2018** [comment]
Thanks for taking time to go in detail of the code and finding out where the bug is. If you are willing I can assign this to you.

**Comment by nanoy42** [comment]
Sure, I can try to give it a go.

**Comment by frankhart2018** [comment]
Ok, assigning this to you.

**Comment by frankhart2018** [comment]
Merged, thanks for your contribution @nanoy42.
