### ISSUE TITLE
[BUG REPORT] Wrong Interpretation of ( ) parenthesis

### ISSUE THREAD

**Issue by DevLokCodes** [cimplec/sim-c#190]
**Describe the bug**
Circular Parenthesis ( ) are not translated correctly for few examples, 
During Translation either one of the closing bracket is lost or Runtime error occurs 

**To Reproduce**
1. Install simc as stated in documentation pip install git+https://github.com/cimplec/sim-c
2. Translate the code given below

`MAIN
    // User input
	var AvgSix = 45 
	var SeventhNumber = 21

	var SumOfSixNumbers = AvgSix * 6
	var AverageOfSevenNumbers = ((SumOfSixNumbers + 21))/SeventhNumber // example [ending closing bracket is lost]
	var abc = (SeventhNumber + SeventhNumber)/AvgSix                   // example [gives Runtime error]
	var bcd = ((SeventhNumber))										   // example [ending closing bracket is lost]
	print("Area of 7 numbers is {AverageOfSevenNumbers} ")

END_MAIN
`

**Expected behavior**
 Images with Correct expected behavior has been added below

**Screenshots**
Eg 1:
![image](https://user-images.githubusercontent.com/69622048/95016924-dafdbd80-0673-11eb-9ada-c95dc617935c.png)
![image](https://user-images.githubusercontent.com/69622048/95017028-6ecf8980-0674-11eb-9c96-adb8150aea82.png)

Eg 2:
![image](https://user-images.githubusercontent.com/69622048/95017059-8eff4880-0674-11eb-9d7c-4deac552a4d4.png)
![image](https://user-images.githubusercontent.com/69622048/95017069-9aeb0a80-0674-11eb-8b86-c6b2beaaca73.png)

Eg 3:
![image](https://user-images.githubusercontent.com/69622048/95017098-ce2d9980-0674-11eb-9426-f91e6e42954d.png)
![image](https://user-images.githubusercontent.com/69622048/95017104-d7b70180-0674-11eb-87c2-a50d51be9c4b.png)

**there are few instances where the operator after the brackets are also lost**

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Comment by frankhart2018** [comment]
Thanks @DevLokCodes for reporting the bug. Please also link this to #66 too. You can comment on that something like:-

Bug reported - Wrong Interpretation of ( ) parenthesis - #190

**Comment by Math-O5** [comment]
@frankhart2018 Can you assign my team on this issue?@JNagasava  @MarcusMedeiros99 and me

**Comment by frankhart2018** [comment]
Hey @Math-O5 sure. Now that hacktoberfest is over, the time is also not constrained to 7 days. Assigning to all of you.
