### ISSUE TITLE
[BUG REPORT] Indentation does not work in Switch cases

### ISSUE THREAD

**Issue by DevLokCodes** [cimplec/sim-c#195]
**Describe the bug**
While the code runs as expected, if Switch case is used in simc the converted C file does not have proper indentations

**To Reproduce**
1. Install simc as stated in documentation pip install git+https://github.com/cimplec/sim-c
2. Translate the code given below

`MAIN
    // User input
	var month = input("Enter a number to find the corresponding month: ", "i")
	
	switch (month) {
		case 1 :
			print("{month}st Month of the Year is January")
			break
		case 2 :
			print("{month}nd Month of the Year is February")
			break
		case 3:
				print("{month}rd Month of the Year is March")
				break
END_MAIN`

**Expected behavior**
The Correct output for the switch should look in this format 

**Screenshots**
This image shows 2 level of indentations but the translated c code does not have any indentation
![image](https://user-images.githubusercontent.com/69622048/95023186-2a0a1980-0699-11eb-9e3b-35f27bf6475f.png)
![image](https://user-images.githubusercontent.com/69622048/95023192-355d4500-0699-11eb-8578-48ee18f16407.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Comment by frankhart2018** [comment]
@DevLokCodes I really don't think this can be considered as a bug. This is more of a feaure for the compiler. We will be releasing proper indentation feature in 0.2 release. Since this seems irrelevant to be counted as bug, closing this. Thanks for pointing this out though.
