### ISSUE TITLE
Bug reported - Unable to compile curly bracket "{" placed in a new line after the if-else statement.

### ISSUE THREAD

**Issue by Darshit-sopho** [cimplec/sim-c#197]
Bug reported - Unable to compile curly bracket "{" placed in a new line after the if-else statement.

Code Example:
![image](https://user-images.githubusercontent.com/24406801/95021386-5b311c80-068e-11eb-9cf8-5a4241754f67.png)
Compiler error:
![image](https://user-images.githubusercontent.com/24406801/95021420-7c920880-068e-11eb-8651-517ff1bea2ab.png)

Operating System: Windows 10

Steps to reproduce:
1. Write the if-else statement as mentioned above.
2. Try to compile the simc code.

_Originally posted by @Darshit-sopho in https://github.com/cimplec/sim-c/issues/66#issuecomment-703282364_

**Comment by frankhart2018** [comment]
Thanks @Darshit-sopho for reporting the bug.

**Comment by i-am-jeetu** [comment]
I want to work on this. Editting parser to skip newlines after detecting `else` will fix the issue.

**Comment by frankhart2018** [comment]
Hey @i-am-jeetu it seems the same thing is to be done for all block type statements like while, for, functions, etc. Assigning this to you. Thanks for showing interest to solve this bug.

**Comment by frankhart2018** [comment]
Merged, thanks for your contribution @i-am-jeetu.
