### ISSUE TITLE
[FEATURE] Add constants to sim-c

### ISSUE THREAD

**Issue by Nazarchamp** [cimplec/sim-c#202]
**The Problem**
I have realized that sim-c contains no constants(PI, TAU, etc.)
This makes it rather inconvenient to do any sort of math that involves circles and you have to manually type in the digits of your constant, which is both tedious and error-prone.

**The solution**
Implement in sim-c a way for you to be able to call constants directly, where on the backend this would convert to the math.h equivalent. For example, writing PI in sim-c would be converted to M_PI in C code(And import math.h).

**Current Workaround**
When I wrote a program to calculate the area of a sphere, I was able to take advantage of the fact that I can declare and initialize a variable in sim-c, then I would initialize that variable to its math.h equivalent constant in C code, and then I was able to use the constant. See /simc-codes/q73.simc. This is a very long and tedious task for something that is already pre built in C's math.h.

I'd be happy to work on this if you approve of it.

I look forward to your response.

**Comment by frankhart2018** [comment]
Sure would love this feature, assigning this to you @Nazarchamp.

**Comment by lucasace** [comment]
Could I take this up?
```
M_E
    Value of e
M_LOG2E
    Value of log2e
M_LOG10E
    Value of log10e
M_LN2
    Value of loge2
M_LN10
    Value of loge10
M_PI
    Value of pi
M_PI_2
    Value of /2
M_PI_4
    Value of /4
M_1_PI
    Value of 1/pi
M_2_PI
    Value of 2/pi
M_2_SQRTPI
    Value of 2/ pi
M_SQRT2
    Value of sqrt(2)
M_SQRT1_2
    Value of 1/sqrt(2) 
```
This are the constants I plan to add

Corresponding names are
```
["pi", "e", "log_e_2", "log_e_10", "ln_2", "ln_10", "pi_2",
                     "pi_4", "pi_4", "1_pi", "2_pi" , "4_PI" , "2_sqrt_pi",
                     "sqrt_2" , "1_sqrt_2"]
```

Do tell If any more are needed

Reference : https://pubs.opengroup.org/onlinepubs/009695399/basedefs/math.h.html

**Comment by PranshulDobriyal** [comment]
@lucasace We do not think it is necessary to add all these constants as many of them can be easily derived by using arithmetic operations. However, we would like to suggest the addition of the following constants in SimC - 
e = Euler's Number
pi 
inf = max possible int value
-inf = smallest possible int value

Please let us know if you are interested in taking up this issue.

**Comment by lucasace** [comment]
Yes I am , As the issue stated constants I naturally thought of math constants,
Are these all , or do you need more constants like tau as mentioned in the issue?
If yes, Kindly give me a list of all those that need to be added

**Comment by PranshulDobriyal** [comment]
@lucasace These will be all. Assigning the issue to you. Looking forward to your contribution

**Comment by frankhart2018** [comment]
Merged, thanks for your contribution @lucasace.
