### ISSUE TITLE
[BUG REPORT] Scope of variable

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#24]
**Describe the bug**
Fails to take scope into account. Final value dicates the initial data type of the var even if they are contradictory in nature.

**To Reproduce**
<ins>simC code</ins>:-
```c
var i = "asb"
MAIN
  var i = 10
  var j = 10
  print(i)
END_MAIN
```

<ins>C Code</ins>:-
```c
#include <stdio.h>
int i = "asb";

int main() {
	int i = 10;
	int j = 10;
	printf("%d", i);

	return 0;
}
```

**Expected behavior**
<ins>C Code</ins>:-
```c
#include <stdio.h>
char* i = "asb";

int main() {
	int i = 10;
	int j = 10;
	printf("%d", i);

	return 0;
}
```

**Comment by adxtop1** [comment]
Hey i want to work on this one

**Comment by frankhart2018** [comment]
Sure, assigning this to you @adxtop1. Thanks for showing interest to contribute.

**Comment by adxtop1** [comment]
Hey, does simC have a concept of scope or it just does line by line translation? 

var i = "asb"
MAIN
  var i = 10
  var j = 10
  var i= 10
  print(i)
END_MAIN


simC translation-


#include <stdio.h>
	int i = "asb";
int main() {
	int i = 10;
	int j = 10;
	int i = 10;
	printf("%d", i);
return 0;
}

**Comment by frankhart2018** [comment]
@adxtop1 no there is no scope as of now
