### ISSUE TITLE
[BUG REPORT] Escape Sequence not supported

### ISSUE THREAD

**Issue by abhisinha2001** [cimplec/sim-c#243]
**Describe the bug**
Whenever an escape sequence is used in simc it gets recognised as a string rather than a character.This further throws an error in c when a character literal is being compared.

**To Reproduce**
```bash 
if(*a!='\0')
Gets converted into:
if(*a!="\0")
```

**Expected behavior**
The null character should be converted to a character rather than a string i.e. ('\0' instead of "\0").

**Comment by lucasace** [comment]
I think I can fix this

**Comment by frankhart2018** [comment]
Sure @lucasace. Assigning this to you. Thanks for showing interest to contribute.

**Comment by frankhart2018** [comment]
Merged, thanks for your contribution @lucasace.
