### ISSUE TITLE
[BUG REPORT] No parantheses check

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#26]
**Describe the bug**
No check for parenthesis pairs and missing parenthesis towards the end

**To Reproduce**
<ins>simC code</ins>:-
```c
MAIN
var i = 1 +(((2)))
END_MAIN
```

<ins>C Code</ins>:-
```c
int main() {
	int i = 1 + (((2);

	return 0;
}
```

**Expected behavior**
<ins>C Code</ins>:-
```c
int main() {
	int i = 1 + (((2)));

	return 0;
}
```

**Comment by zurda** [comment]
Hi @frankhart2018 , I'd love to give this a try if it's up for grabs?

**Comment by frankhart2018** [comment]
Sure @zurda. Assigning this to you. Thanks for showing interest to contribute.

**Comment by Math-O5** [comment]
@frankhart2018 May I try this one?
