### ISSUE TITLE
[FEATURE] Allow C code to be written inside simC

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#28]
**Is your feature request related to a problem? Please describe.**
Allowing user to write C code inside simC, this will be just copied and pasted into compiled C code without checking for syntax or compiling.

**Describe the solution you'd like**
Add two tokens BEGIN_C and END_C between which C code will be written, this should be directly pasted into appropriate location in compiled C code by simC compiler.

**simC Code Example**
```c
MAIN
    var i = 0
    print(i)
    
    BEGIN_C
        int c = 10;
        int* ptr = &c;
        printf("%d\n", *ptr);
    END_C
END_MAIN
```

**Comment by YJDoc2** [comment]
What if add BEGIN_C, END_C, and RAW_C in lexical_analyzer.py and after encountering BEGIN_C, keep an internal switch, which if true return all tokens found as type RAW_C, until encountered END_C. Then add RAW_C type tokens without changes to C code in compiler.py.

**Comment by frankhart2018** [comment]
Yeah was thinking of something like this. Thanks @YJDoc2 for sharing your thoughts. Do you want to work in this?

**Comment by YJDoc2** [comment]
Sure, I'd like to work on this.

**Comment by frankhart2018** [comment]
Ok assigning this to you.

**Comment by YJDoc2** [comment]
Hey, the test.simc file only contains ':' . trying to run run.sh gives error, and test.sh echos blank output. Is this intentional or error?

**Comment by frankhart2018** [comment]
You can ignore them. We were experimenting with some things.

**Comment by YJDoc2** [comment]
I have made PR #107 for this.

**Comment by dhairyaj** [comment]
Thanks @YJDoc2 , we will check this out and then take further action. Thanks for the contribution.

**Comment by frankhart2018** [comment]
Merged, thanks for your contribution.
