### ISSUE TITLE
[FEATURE] Implement sizeof

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#29]
**Is your feature request related to a problem? Please describe.**
Implement sizeof operator to return the size of a variable.

**Describe the solution you'd like**
Whenever sizeof is called the type of the variable should be extracted from symbol table and based on this type return the size. Files to be changes for adding this are lexical_analyzer, parser, and compiler.

<b>Note</b>:- The size should not be static for every machine (e.g. size of an int variable should not return 4 for every machine), the result should be machine dependant and should be computed accordingly.

**simC Code Example**
```c
MAIN
    var i = 3.14159
    var size = sizeof(i)
    print(size)
END_MAIN
```

**Comment by JNagasava** [comment]
Hey, can you assign me on this issue ?

**Comment by frankhart2018** [comment]
Sure @JNagasava. Thanks for showing interest to contribute.

**Comment by Deep2631** [comment]
sir i want to work with this project

**Comment by frankhart2018** [comment]
Sure @Deep2631 assigning this to you. Let me know the implementation details before starting.

**Comment by aum-singhal** [comment]
Sir I also want to contribute on this project If you allow

**Comment by frankhart2018** [comment]
Sure @aum-singhal assigning this to you too.
