### ISSUE TITLE
[FEATURE] Explicit typecasting

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#30]
**Is your feature request related to a problem? Please describe.**
Explicit casting of types from by the user.

**Describe the solution you'd like**
Syntax will be similar to that of python (e.g. int(3.14159)). After successful type casting the type for the corresponding value should be updated in symbol table.

**simC Code Example**
```c
MAIN
    var i = 3.14159
    var int_i = int(i)
    print(int_i)
END_MAIN
```

**Comment by ilyasmg** [comment]
I'd like to take this. It'll be helpful of you can give me hint on which files should be changed :D

**Comment by frankhart2018** [comment]
Sure @ilyasmg. Assigning this to you. So, to add this functionality you will have to make changes in the lexical analyzer (simc/lexical_analyzer.py) so that you identify these things as keywords, then you will have to add this support in the parser (simc/simc_parser.py) where you will parse these in the ```expression()``` function. In the compilation part (simc/compiler.py) you will just have to change the call ```int(i)``` to ```(int)(i)``` as this is something that C accepts. Thanks for showing interest to contribute.

**Comment by ilyasmg** [comment]
in the lexical_analyzer should I just add each data type in the is_keyword() or should I do also something else?

**Comment by frankhart2018** [comment]
Please go through the codebase, its fairly simple to read.

**Comment by ilyasmg** [comment]
I went through the codebase.
I'm a bit confused..in lexical_analyzer I added "int" in the is_keyword() function
then in simc_parser.py inside the parser() function I added   
`elif tokens[i].type == "int":
            op_value, op_type, i, func_ret_type = expression(...)`
And in the compiler.py I added
```
elif opcode.type == "int":
            code += "(" + opcode.val + ")"
```
When I run an example I get "Error: Expected 0 parameters but got 1 parameters in function int"
I'm not sure if it's because my assumption that typecasting is kind of function is wrong or it's due to compiling the changed code.
I installed the repository using `pip install git+https://github.com/cimplec/sim-c`, how do I do to modify the binary to use my modified code?

**Comment by frankhart2018** [comment]
Mostly the error is because you installed using the code in this main repository, and in that int isn't a keyword so it is getting identified as an identifier and hence as a function later. To use a development version of simc (for your code), follow these steps (you should be inside sim-c repository to execute the second command):-

```bash
user@programmer~:$ pip uninstall simc -y
user@programmer~:$ python setup.py install
```

**Comment by ilyasmg** [comment]
Hi thanks,
I'm getting `Error: Required expression after assignment operator` for the second token `var` (int_i) in the `var_statement()` function..I had a look but I'm not sure if I need to modify something there..`# Check if expression follows = in var statement` is causing the problem.
Not sure if I'll finish in a week, I'm not finding it very easy this task D:

**Comment by frankhart2018** [comment]
If you need more time you can take one more week.

**Comment by ilyasmg** [comment]
I should also update the symbol table right?

**Comment by Gaurav7888** [comment]
@frankhart2018  Hi I want to work upon this issue.

**Comment by frankhart2018** [comment]
Sure assigning this to you @Gaurav7888. Thanks for showing interest to contribute.
