### ISSUE TITLE
[FEATURE] Implement typeof

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#31]
**Is your feature request related to a problem? Please describe.**
Implement typeof operator in simC.

**Describe the solution you'd like**
Simply return the type of variable from symbol table. When typeof is called on a variable.

**simC Code**
```c
MAIN
    var i = 3.14159
    typeof(i)
END_MAIN
```

**Comment by codeSalazar12** [comment]
Hey can i help?

**Comment by dhairyaj** [comment]
Sure, why not!
Thank you :)

**Comment by MarcusMedeiros99** [comment]
May I get assigned to this issue?

**Comment by frankhart2018** [comment]
Sure @MarcusMedeiros99. Thanks for showing interest to contribute.

**Comment by sakshikhachane** [comment]
@frankhart2018 I would like to work on this issue.

**Comment by frankhart2018** [comment]
Sure @sakshikhachane. Assigning this to you. Do let me know the implementation details before you start working :)

**Comment by ami-harry** [comment]
@frankhart2018 I would like to work on this issue

**Comment by sohitdon** [comment]
Can i contribute on this please @frankhart2018

**Comment by frankhart2018** [comment]
Sure assigning this to both of you too @ami-harry @sohitdon. Let me know the implementation details before starting.

**Comment by Deep2631** [comment]
sir i want to work with this project

**Comment by Deep2631** [comment]
this pi math

**Comment by ArjitSahu** [comment]
Sir I want also to work on this issue

**Comment by Deep2631** [comment]
Is your feature request related to a problem? Please describe.
Implement typeof operator in simC.

Describe the solution you'd like
Simply return the type of variable from symbol table. When typeof is called on a variable.

simC Code

MAIN
    var i = 3.14159
    typeof(i)
END_MAIN


typeof 3.14 === 'number';

**Comment by frankhart2018** [comment]
Sure asigning this to you too @ArjitSahu. Post implementation details before starting. 

@Deep2631 do you want to work in this too.

**Comment by Deep2631** [comment]
yes sir

**Comment by ami-harry** [comment]
@frankhart2018 
typeof is an inbuilt function that tales about the type of the variable value.
the type of the variable depends upon the value it is containing and to check the type of variable we use typeof(var_name)
this method returns type of variable

**Comment by frankhart2018** [comment]
Sure assigning this to you too. Please post the full implementation detail @Deep2631.

**Comment by frankhart2018** [comment]
Won't be accepting any more people in this issue, will stop at 5.

**Comment by frankhart2018** [comment]
@ami-harry by implementation detail I meant how you would implement this in simC code base. What would the lexical analysis, parsing and compilation work.

**Comment by ami-harry** [comment]
sorry, I didn't get you
please elaborate what exactly I have to do?

**Comment by frankhart2018** [comment]
@ami-harry I would suggest you to check implementation of some functionality, like print statement. This would make things clearer. Otherwise it would be tough for me to explain 😃

**Comment by sohitdon** [comment]
i am not able to understand exactly what is this sim-c but in javascript typeof operator returns the type of variable like var i = 3.14159
    console.log(typeof(i))

this will return numbers

**Comment by ami-harry** [comment]
MAIN
    var i = 3.14159
    typeof(i)
END_MAIN


//we will do like this

var i = 3.14159
console.log(typeof(i))

//save and run this file
//it will give a number because i is containing a number

**Comment by ArjitSahu** [comment]
var i = 3.14159
console.log(typeof(i))
Answer==number

**Comment by Deep2631** [comment]
The PI property returns the ratio of a circle's area to the square of its radius, approximately 3.14
type of number

**Comment by frankhart2018** [comment]
Discussion for this issue - https://github.com/cimplec/sim-c/discussions/430
