### ISSUE TITLE
[FEATURE] Default parameters in functions

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#34]
**Is your feature request related to a problem? Please describe.**
Add support for default parameters in functions in simC.

**Describe the solution you'd like**
Syntax will be similar to that of C.

**simC Code Example**
```c
fun sum(a, b=2) {
    return a + b;
}

MAIN
    var result_1 = sum(1)
    print(result_1)
    
    result_1 = sum(1, 3)
    print(result_1)
END_MAIN
```

**Comment by ThomasBollmeier** [comment]
If that's okay for you, I would like to work on this issue.

**Comment by frankhart2018** [comment]
Sure @ThomasBollmeier. Assigning this to you. Thanks for showing interest to contribute.

**Comment by frankhart2018** [comment]
Merged, thanks for your contribution @ThomasBollmeier.
