### ISSUE TITLE
[BUG REPORT] Functions Allow declaration of braces in same line 

### ISSUE THREAD

**Issue by Math-O5** [cimplec/sim-c#342]
**Describe the bug**
Functions can not be declared with braces in the same line of declaration showed in documentation

**To Reproduce**

Try:

```
fun sum(you, me) {
      return you + me
}
```
Throw an error, expected new line after sum(), but it should be allowed.

To success, the code must be as:
```
fun sum(you, me) 
{
      return you + me
}
```

What must change?
Allow this declaration of the documentation too. Or at least change documentation.

**Comment by Math-O5** [comment]
@frankhart2018 May I be assigened? huehue

**Comment by frankhart2018** [comment]
Thanks for reporting this issue @Math-O5. Sure assigning this to you.
