### ISSUE TITLE
[FEATURE] Array indexing - right side (static array)

### ISSUE THREAD

**Issue by dhairyaj** [cimplec/sim-c#346]
**Describe the solution you'd like**
Indexing an array when in right hand side of expression. Changes to be made in expression function.

<strong>Syntax</strong>
<array_name>[index] 

**Example**
var a = arr[0]

**Comment by ami-harry** [comment]
I want to contribute to this issue

**Comment by frankhart2018** [comment]
Sure @ami-harry assigning this to you.

**Comment by ayushi-get** [comment]
i would like to contribute to this issue .

**Comment by frankhart2018** [comment]
Sure @ayushi-get. Assigning this to you.

**Comment by Math-O5** [comment]
@frankhart2018 I think this was closed by mistake!

**Comment by frankhart2018** [comment]
Merged.
