### ISSUE TITLE
[FEATURE] Add README in different languages.

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#35]
REAMDE goes inside **readme-lang** folder. The naming convention used is **README-(language name).md** where (language name) is the name of language in which README is being translated. 

Note: Discuss with a maintainer in this thread before starting to translate the README.

**Comment by andrefpoliveira** [comment]
Hey :) I would like to work on this and translate the README.md to Portuguese. Where do you want me to store the translated version?

**Comment by frankhart2018** [comment]
Hey @andrefpoliveira thanks for reaching out. You can put your readme in the readme-lang folder. Make sure to name the readme file in the following format:- README-<language name>.md where <language name> is the name of the language you are translating into.

**Comment by UtkarshChaurasia** [comment]
I would like to translate README.md to Hindi.

**Comment by frankhart2018** [comment]
Sure go ahead @UtkarshChaurasia. Please convert the README in readme-lang (readme-lang/README-eng.md) into hindi. Thanks.

**Comment by reveurguy** [comment]
i would like to covert README to French.

**Comment by frankhart2018** [comment]
Hey @reveurguy sure. Thanks for showing interest to contribute. Please check the README file in readme-lang (readme-lang/README-eng.md).

**Comment by Xetaphore** [comment]
Hey @frankhart2018 , I would like to translate this in German. Thanks in advance.

**Comment by dhairyaj** [comment]
@Xetaphore , sure, you can work on the README. Refer to the readme-lang/README-eng.md.
