### ISSUE TITLE
[BUG REPORT] simc test.c gives an unexpected error

### ISSUE THREAD

**Issue by shobhit10058** [cimplec/sim-c#350]
**Description of the bug**
when simc is run with a file not with .simc extension it gives an unexpected error 
```
Traceback (most recent call last):
  File "/home/shobhit/.local/bin/simc", line 8, in <module>
    sys.exit(run())
  File "/home/shobhit/.local/lib/python3.8/site-packages/simc/simc.py", line 25, in run
    error("Incorrect file extension", line_num)
NameError: name 'line_num' is not defined
```
NameError should not come. 

**Steps To Reproduce**
simply run simc test.c.

**Expected behavior**
It should simply give Incorrect file extension

**Comment by shobhit10058** [comment]
We can simply fix it by removing line_num with -1 or something.

**Comment by frankhart2018** [comment]
Hey thanks @shobhit10058 for submitting the bug report, do you want to work on this?

**Comment by shobhit10058** [comment]
yes

**Comment by shobhit10058** [comment]
I think the suggestion is enough, so should I add it -1.

**Comment by frankhart2018** [comment]
Yeah that would work, assigning this to you.

**Comment by frankhart2018** [comment]
Merged.
