### ISSUE TITLE
[FEATURE] Add structure declaration

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#356]
**Describe the solution you'd like**
To add support only struct <structure-name> line has to be parsed as we use a selectively recursive recursive descent parser which does not require unnecessary recursion.  

**Todo**
1) Identify struct as a keyword
2) Parse the line - struct <structure-name>
3) Compile the line - struct <structure-name>

For reference look at implementation of loops and function definition.

**Comment by 10Kaiser10** [comment]
I would like to work on this issue, please assign me.

**Comment by frankhart2018** [comment]
Sure @10Kaiser10.

**Comment by frankhart2018** [comment]
Merged.
