### ISSUE TITLE
[FEATURE] Instantiating structure in the definition

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#357]
**Describe the solution you'd like**
Add structure instantiation to simC. 

**Example**
struct hello {
    var a
    var b
} <struct_var>

**Todo**

1) Make changes in parsing of } to take the variable into account too, creating a separate opcode might be helpful.
2) Compile the } accordingly.

**Comment by 10Kaiser10** [comment]
I would like to work on this issue. Can you please assign me?

**Comment by 10Kaiser10** [comment]
Hi, please assign me to this issue.

**Comment by frankhart2018** [comment]
Sure @10Kaiser10.

**Comment by aum-singhal** [comment]
Sir I will be very much interested to contribute on this project but can you help that what outcome are you expecting when someone write that code?

**Comment by frankhart2018** [comment]
Merged.
