### ISSUE TITLE
[FEATURE] Structure instantiation for a local scope

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#358]
**Is your feature request related to a problem? Please describe.**
Instantiating structure in simC.

**Example**
Assuming structure hello already defined:-

hello h

**Todo**

1) Make changes in variable declaration in parser to take this into account, creating a new opcode might be helpful.
2) Compile the code according to this newly created opcode.

**Comment by sourav-suku** [comment]
Hi @frankhart2018 .Please assign this to me

**Comment by aum-singhal** [comment]
Sir I am very much interested to contribute on this project but just wanted to confirm that by the structure, you mean the linked lists structure or you anything else

**Comment by frankhart2018** [comment]
Yeah structures in C. This issue is for implementation of structure instantiation. Implementation of structure declaration is done, you can take a look at that to get a better idea. Would you like to work on this?

**Comment by aum-singhal** [comment]
yeah sure

**Comment by frankhart2018** [comment]
Assigning this to you @aum-singhal.
