### ISSUE TITLE
[FEATURE] Add character input to simc

### ISSUE THREAD

**Issue by Chasmiccoder** [cimplec/sim-c#370]
So far, simc deals with strings properly, but it still does not have support for C characters.
Implementation of characters:
simc code - 
var c = input( "Enter a character: ", "c" )
print( c )

Corresponding C code - 
char c;
printf( "Enter a character: " );
scanf( " %c", &c );
printf( "%c", c );

Note how there is a space in the scanf( ) statement in the C code. This is because if the previous line has a
newline character ( '\n' ), then scanf( ) will consume it immediately. This is why the space needs to be there.

**Comment by InfiniteVerma** [comment]
I'll like to work on this.

**Comment by Math-O5** [comment]
@InfiniteVerma Already, thanks by the interest!

**Comment by yashshah14093** [comment]
@Math-O5 @frankhart2018 Can I make a pull request for this issue? I have solved this issue and checked by running an example mentioned in this issue. So Could you assign this issue to me, please?

**Comment by frankhart2018** [comment]
Sure assigning this to you too @yashshah14093.

**Comment by frankhart2018** [comment]
Merged.
