### ISSUE TITLE
[BUG REPORT] Function cannot be called multiple times

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#400]
**Describe the bug**
A function defined in simC can be called once currently, when calling it again it throws error.

**Comment by Chasmiccoder** [comment]
Hi there! @frankhart2018 
For some reason calling the function twice is already working for me.
Simc Code:
fun sum ( a, b ) {
    return a + b
}

MAIN 
    var A = input( "Enter an integer: ", "i" )
    var B = input( "Enter another integer: ", "i" )

    //C = sum ( A, B )
    var C = sum( A,B )
    print( "SUM: " )
    print( C )
    print( "\n" )

    var D = sum( C,B )

    print( "SUM2: " )
    print( D )
    print( "\n" )

END_MAIN


Corresponding C Code:
#include <stdio.h>

int sum(int a, int b) {

	return a + b;
}

int main() {
	int A;
	printf("Enter an integer: ");
	scanf("%d", &A);
	int B;
	printf("Enter another integer: ");
	scanf("%d", &B);
	// C = sum ( A, B ) 
	int C = sum(A, B);
	printf("SUM: ");
	printf("%d", C);
	printf("%c", '\n');
	int D = sum(C, B);
	printf("SUM2: ");
	printf("%d", D);
	printf("%c", '\n');

	return 0;
}


Output of C Code:
![image](https://user-images.githubusercontent.com/62545147/103189958-f6840780-48f4-11eb-97f8-37860074e928.png)

**Comment by frankhart2018** [comment]
Yeah now it is working for me too, weird 😄. Closing this then.
