### ISSUE TITLE
[BUG REPORT] Fails to account for missing right braces"}" in nested blocks.

### ISSUE THREAD

**Issue by 10Kaiser10** [cimplec/sim-c#402]
**Describe the bug**
Does not raise an error when there is an unequal number of right and left braces in nested blocks of code.

**To Reproduce**
SimC code:
```python
MAIN
{
    var a = 1
    {
        var b = a+1
    }
    print(b)
END_MAIN
```

C Code:
```C
#include <stdio.h>
int main() {
{
	int a = 1;
{
	int b = a + 1;
	}
	printf("%d", b);

	return 0;
}
```

**Expected behavior**
Should raise an error

**Comment by Chasmiccoder** [comment]
Can we conduct a check (to see if the braces are balanced) at the beginning of compilation using a stack?

**Comment by Chasmiccoder** [comment]
Can I try this out?

**Comment by sourav-suku** [comment]
In the "LexicalAnalyser.py" balancing check is done only for '(' and ')'

**Comment by Chasmiccoder** [comment]
> In the "LexicalAnalyser.py" balancing check is done only for '(' and ')'

Okay @sourav-suku 
So we just need to account for { } , right?

**Comment by sourav-suku** [comment]
@Chasmiccoder 
Ya.I guess so.
We should even account for [ ] as its case is similar to { }.

**Comment by Math-O5** [comment]
@Chasmiccoder Assigned to you.
