### ISSUE TITLE
[BUG REPORT] Commands outside main not throwing error

### ISSUE THREAD

**Issue by Math-O5** [cimplec/sim-c#415]
**Describe the bug**
Command out of scope, like "print, for, while" not throw error when declared outside a function or MAIN. 

**To Reproduce**

Case 1:
```
// Outside functions, should NOT be control code here
print("A") 
var i = 0 
while(i < 3) 
    print(i)

MAIN
   // code CAN BE here
END_MAIN
```
Case 2: 
```
// This should NOT be allowed,
fun sum(a, b) 
      return a + b
      return a + b 
```
Case 3:
```
// Variable CAN BE declared as global
var named 
```

Case 4:
```
fun functions( ) { 
  // code CAN BE here
}
```

Case 5:
```
MAIN
   // code CAN BE here
END_MAIN
```

Case 6: 
```
// This should be allowed
fun sum(a, b) 
      return a + b
```

**Expected behavior**
Throw error when code is not used correctly. Expected this code only work when declared inside a scope of a function like "fun", "MAIN", exception are variables, which can be global. 

**Please, follow the CONTRIBUTION.md instructions, the name of branch, clear code and comments on it.**

**Comment by nayaldivya** [comment]
Hello, I would like to work on this issue. Can you assign this to me?

**Comment by frankhart2018** [comment]
Sure assigning this to you @nayaldivya.
