### ISSUE TITLE
[BUG REPORT] Functions inside functions

### ISSUE THREAD

**Issue by Math-O5** [cimplec/sim-c#416]
**Describe the bug**
Sim-C is wrongly allowing declarations of function inside function, but C does not accept it.  
 
**To Reproduce**

Sim-C code: 
```
fun joy( ) {
     
     // This function should not be allowed, stop this evil behavior
     fun evil ( ) {
     }

}

MAIN

  // This function should not be allowed here, stop this evil behavior
   fun evil_two( ) {
   }

END_MAIN

```

Output: C code!

**Expected behavior**
Throw a message error to user. 

Please, follow the CONTRIBUTION.md instructions.

**Comment by frankhart2018** [comment]
Merged #421.
