### ISSUE TITLE
[BUG REPORT] Incorrect Usage of Check Braces Flag

### ISSUE THREAD

**Issue by Chasmiccoder** [cimplec/sim-c#417]
**Describe the bug**
The function of lines 74,75 is unclear, as the lines are ambiguous. 
Basically, we check if variable found_right_brace is True. And then we are assigning the same variable a Truth value.

**To Reproduce**
Go to conditional_parser.py
Go to line 74,75.

**Screenshots**
![image](https://user-images.githubusercontent.com/62545147/102334044-3e7d6300-3fb4-11eb-91ea-4d845f2e156f.png)

**Comment by Math-O5** [comment]
@Chasmiccoder I think this is not used, you wanna do the PR?

**Comment by Chasmiccoder** [comment]
> @Chasmiccoder I think this "if" is not used, the while should just loop until reach "right_brace". You wanna do the PR? This also happens in others parses.

Yea sure! @Math-O5 
So I just need to remove those two lines, right?
