### ISSUE TITLE
[BUG REPORT] array declaration gives error

### ISSUE THREAD

**Issue by shobhit10058** [cimplec/sim-c#427]
**Describe the bug**
When a array is declared a unusual error is shown.
![image](https://user-images.githubusercontent.com/56156171/103158421-a8331380-47e3-11eb-99a0-1fe74d692c5f.png)

**To Reproduce**
just run the following code -
```
MAIN
	var name[30] = {1,2,3}
END_MAIN
```

**Expected behavior**
No such error should come

**Comment by frankhart2018** [comment]
@Math-O5 can you take a look at this.

**Comment by shobhit10058** [comment]
I have fixed this it was just that balanced_brackets_stack and top were used in lexical analyser. They should be used with self

**Comment by frankhart2018** [comment]
Oh ok then you can make a PR :)

**Comment by frankhart2018** [comment]
Merged.
