### ISSUE TITLE
[FEATURE] Redundant code in array_initializer (array_parser.py)

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#433]
**Describe the solution you'd like**
The array initializer list parsing can be done using expression function but has been implemented again which is redundant. Update array_initializer in array_parser.py to use expression() from sim_parser.py to parse expression instead of repeating the same logic.

**Comment by Chasmiccoder** [comment]
Hi there!
Can I work on this?

**Comment by frankhart2018** [comment]
Sure @Chasmiccoder. Assigning this to you.

**Comment by Math-O5** [comment]
@Chasmiccoder I don't know if it is important, `i_temp` we use name `idx` on others files.

**Comment by frankhart2018** [comment]
Merged.
