### ISSUE TITLE
[BUG REPORT] Incorrect error message when function is not defined

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#437]
**Describe the bug**
When a function is not defined but is called the error message should be like:- "Function <func-name> is not defined", but it throws an error regarding the mismatch of number of formal and actual params. 

**sim-C Code**
```
MAIN
    sum(1, 2)
END_MAIN
```

**Error Message**

[Line 2] Error: Expected not more than 0 arguments but got 2 in function sum

**Comment by nishihere19** [comment]
Which file has to be corrected?

**Comment by frankhart2018** [comment]
You need to look into parser/simc_parser.py and parser/function_parser.py. Would you like to work on this?

**Comment by nishihere19** [comment]
Yeah. I would like to do it.

**Comment by frankhart2018** [comment]
Assigning this to you then @nishihere19.
