### ISSUE TITLE
[BUG REPORT] stdio.h gets included for array/pointer declaration + assignment

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#447]
**Describe the bug**
When compiling a code containing only a single line of array declaration + assignment, the resulting C code has stdio.h included which should not be the case. The same issue arises in pointer declaration + assignment. Handle both these cases to not include stdio.h.

**simC Code**
```
var a[2] = {1, 2}
```

**C Code**
```c
#include <stdio.h>
	int a[2] = {1,2};
```

**Expected C Code**
```c
	int a[2] = {1,2};
```

**Comment by Chasmiccoder** [comment]
Can I work on this? @frankhart2018

**Comment by frankhart2018** [comment]
Sure assigning this to you @Chasmiccoder.
