### ISSUE TITLE
[BUG REPORT] Cloned repo gets deleted on running tests

### ISSUE THREAD

**Issue by sayandip18** [cimplec/sim-c#451]
**Describe the bug**
I just faced something very strange. I cloned the test-suite and ran `simc-test`. On running the test, the cloned sim-c repository on my system got deleted all of a sudden.

**To Reproduce**

1. Clone the sim-c repo
2. Install the test-suite.
3. Run `simc-test`
4. You'll see that both the sim-c repository and the test-suite repository are no longer there in your system.

**Expected behavior**
Neither of the repos should get deleted.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by frankhart2018** [comment]
Can you create this issue in https://github.com/cimplec/test-suite. Would be more relevant there. Closing this one.
