### ISSUE TITLE
[FEATURE] Pretty print symbol table

### ISSUE THREAD

**Issue by frankhart2018** [cimplec/sim-c#478]
**Describe the feature and the solution**
Currently if we print the symbol table it prints the dictionary, it would be easier if it was displayed as proper table format. This functionality can be added by adding a __str__ magic method to symbol table class.

**Comment by Chasmiccoder** [comment]
Hi there!
Can I work on this feature?

**Comment by frankhart2018** [comment]
Sure @Chasmiccoder.
