### ISSUE TITLE
[FEATURE] Report bugs

### ISSUE THREAD

**Issue by PranshulDobriyal** [cimplec/sim-c#66]
Report any bug you encounter while using SimC

**Format of Bug Submission**
The format can be found in the file bugs/format.txt. 
Separate files should be made for different bugs. The extension of all the bug-reports should be .txt

**Comment by lucasace** [comment]
Bug reported - For loops not accepting variables as starting or ending variable - #133

**Comment by adenashameem** [comment]
Bug reported - When printing with variables embedded in strings all occurrences of the variable in the string are converted into format specifier #149.

**Comment by Martianmellow12** [comment]
Bug reported - Compiler throws warnings when an input statement is used with no print statements - #137.

**Comment by Martianmellow12** [comment]
Bug reported - Using "s" to read in a string doesn't generate the proper C code - #183.

**Comment by nanoy42** [comment]
Bug reported - OR (||) is not translated correctly - #189

**Comment by Darshit-sopho** [comment]
Bug reported - Unable to compile curly bracket "{" placed in a new line after the if-else statement.

Code Example:
![image](https://user-images.githubusercontent.com/24406801/95021386-5b311c80-068e-11eb-9cf8-5a4241754f67.png)
Compiler error:
![image](https://user-images.githubusercontent.com/24406801/95021420-7c920880-068e-11eb-8651-517ff1bea2ab.png)

Operating System: Windows 10

Steps to reproduce:
1. Write the if-else statement as mentioned above.
2. Try to compile the simc code.

**Comment by DevLokCodes** [comment]
Bug reported - Wrong Interpretation of ( ) parenthesis in cases of multiple brackets - #190

**Comment by ThomasBollmeier** [comment]
Bug reported - Function definition allows non-identifiers as parameters - #204.
